<a href="https://colab.research.google.com/github/Tom-Lennox/Kaggle/blob/master/Pytorch_20200714.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## ▼ これで何ができるのか？を軸に作成すべし。

# GPU: 編集>ノートブックの設定

# https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

# 【行ったこと】

## ▼ Pytorch
Pytorch = GPUを活用できる計算パッケージ  
｜ >> NumPy  

|【numpy】|【pytorch】|
| :---- | :---- |
|ndarray|Tensor|
|reshape|view|



In [1]:
from __future__ import print_function
import torch

## ▼ 初期化されていない
x = torch.empty(5, 3)
print(x)

## ▼ ランダム作れる
x = torch.rand(5, 3)
print(x)

## ▼ ゼロにできる
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

## ▼ 任意の値に書き換えられる
x = torch.tensor([5.5, 3])
print(x)


## ▼ 1もある。 + dyyleが指定できる。
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

## ▼ 正規乱数（正規乱数とは正規分布に従う乱数）も使える
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

print(f'x.size(): {x.size()}')

# --
# 加算・減算は省略。
# --

print(f'x[:, 1]: {x[:, 1]}')

tensor([[3.4049e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])
tensor([[0.1130, 0.3878, 0.6677],
        [0.6343, 0.7565, 0.2563],
        [0.0139, 0.4492, 0.3307],
        [0.5117, 0.5592, 0.3279],
        [0.9453, 0.1878, 0.6837]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2187, -0.1764, -1.4818],
        [ 1.2188,  1.8799, -0.4830],
        [ 0.0332, -0.2635, -2.7475],
        [-0.6588,  0.7260, -0.5204],
        [ 0.3089,  1.5760,  0.1252]])
x.size(): torch.Size([5, 3])
x[:, 1]: tensor([-0.1764,  1.8799, -0.2635,  0.7260,  1.5760])


In [ ]:
x = torch.rand(5, 3)
print(x)
print('--')
y = torch.rand(5, 3)
print(y)
print('--')
print(x + y)
print('--')
print('\n--\n', torch.add(x, y))ｗ

print('## ▼ torch.add(x, y)')
print(torch.add(x, y))

## ▼ 
result = torch.empty(5, 3)
print('## ▼ result')
print(result)

print(x)
print(x[:, 0])
print(x[0, :])

tensor([[0.0668, 0.7798, 0.5598],
        [0.8372, 0.9676, 0.4415],
        [0.9175, 0.5123, 0.8637],
        [0.6254, 0.8056, 0.6659],
        [0.1961, 0.8145, 0.3054]])
--
tensor([[0.1816, 0.8743, 0.5231],
        [0.3299, 0.6653, 0.2165],
        [0.4801, 0.4947, 0.0226],
        [0.4595, 0.9997, 0.9303],
        [0.1785, 0.1962, 0.3352]])
--
tensor([[0.2484, 1.6541, 1.0829],
        [1.1672, 1.6329, 0.6579],
        [1.3975, 1.0070, 0.8863],
        [1.0849, 1.8053, 1.5962],
        [0.3746, 1.0107, 0.6406]])
--

--
 tensor([[0.2484, 1.6541, 1.0829],
        [1.1672, 1.6329, 0.6579],
        [1.3975, 1.0070, 0.8863],
        [1.0849, 1.8053, 1.5962],
        [0.3746, 1.0107, 0.6406]])
## ▼ torch.add(x, y)
tensor([[0.2484, 1.6541, 1.0829],
        [1.1672, 1.6329, 0.6579],
        [1.3975, 1.0070, 0.8863],
        [1.0849, 1.8053, 1.5962],
        [0.3746, 1.0107, 0.6406]])
## ▼ result
tensor([[5.3036e-36, 0.0000e+00, 1.0829e+00],
        [1.1672e+00, 1.6329e+00, 6.5793e-01],
      

In [27]:
## ▼ reshape ⇒ view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(2, 8)
print(x)
print(y)
print(z)

## ▼ torch tensor ⇒ numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

## ▼ 加算（全て）
a.add_(1)
print(a)
# 自動で変更されるのか。
print(b)

print('--')
## ▼ numby ⇒ torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 10, out=a)
print(a)
print(b)



tensor([[ 1.5024, -0.4652, -1.2725, -0.7053],
        [ 0.9709, -0.1272,  1.5684,  0.2480],
        [ 0.0989, -0.8207, -0.4089, -0.4665],
        [-1.2593, -1.3327, -0.2525,  2.0236]])
tensor([ 1.5024, -0.4652, -1.2725, -0.7053,  0.9709, -0.1272,  1.5684,  0.2480,
         0.0989, -0.8207, -0.4089, -0.4665, -1.2593, -1.3327, -0.2525,  2.0236])
tensor([[ 1.5024, -0.4652, -1.2725, -0.7053,  0.9709, -0.1272,  1.5684,  0.2480],
        [ 0.0989, -0.8207, -0.4089, -0.4665, -1.2593, -1.3327, -0.2525,  2.0236]])
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
--
[11. 11. 11. 11. 11.]
tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


In [32]:
## ▼ [must] GPU: ON
# if torch.cuda.is_availiable():
if torch.cuda.is_available():
    print('--')
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!