<a href="https://colab.research.google.com/github/Tom-Lennox/Kaggle/blob/master/Pytorch_20200714.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## ▼ これで何ができるのか？を軸に作成すべし。


# 【行ったこと】

## ▼ Pytorch
Pytorch = GPUを活用できる計算パッケージ  
｜ >> NumPy  

|【numpy】|【pytorch】|
| :---- | :---- |
|ndarray|Tensor|


In [5]:
from __future__ import print_function
import torch

x = torch.empty(5, 3)
print(x)

## ▼ ランダム作れる
x = torch.rand(5, 3)
print(x)

## ▼ ゼロにできる
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

## ▼ 任意の値に書き換えられる
x = torch.tensor([5.5, 3])
print(x)


## ▼ 1もある。 + dyyleが指定できる。
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

## ▼ 正規乱数（正規乱数とは正規分布に従う乱数）も使える
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

print(f'x.size(): {x.size()}')

tensor([[1.8934e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [3.7293e-08, 5.0063e-01, 8.0322e-01],
        [6.6210e-01, 6.1457e-01, 7.6759e-01]])
tensor([[0.2258, 0.4634, 0.9396],
        [0.3003, 0.6031, 0.1734],
        [0.7687, 0.7450, 0.1817],
        [0.2335, 0.2789, 0.5666],
        [0.7142, 0.3469, 0.3456]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7236, -0.6583,  1.0527],
        [-0.7588, -1.0281, -1.4376],
        [ 0.3660, -1.0425, -0.6490],
        [ 1.1625,  1.1701, -0.3796],
        [ 1.1942, -0.8872,  0.6697]])
x.size(): torch.Size([5, 3])
